FROM nginx
RUN apt-get update && apt-get install -y iputils-ping
RUN apt-get update && apt-get install dnsutils -y
RUN apt-get update && apt-get install -y iproute2
RUN apt-get update && apt-get install -y vim
RUN apt-get update && apt-get install -y net-tools
